version: 3
#endpoint: http://ec2-3-34-49-178.ap-northeast-2.compute.amazonaws.com:8080
endpoint: https://rare-gobbler-36.hasura.app
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
