version: 3
endpoint: https://rare-gobbler-36.hasura.app
admin_secret: WGOqf2frsV2RDq7ZL2pCHXLAOyTGiYZS3uRCHf3dA3cLQucdK1JvV39Xocd8e1XA
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
